// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
    appId: '1:851479812076:web:297821a97298787a6712c9',
    messagingSenderId: '851479812076',
    projectId: 'ets-ppb-1512',
    authDomain: 'ets-ppb-1512.firebaseapp.com',
    storageBucket: 'ets-ppb-1512.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
    appId: '1:851479812076:android:be08efb8e1cfc1706712c9',
    messagingSenderId: '851479812076',
    projectId: 'ets-ppb-1512',
    storageBucket: 'ets-ppb-1512.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:851479812076:ios:8ba04be44f9afb306712c9',
    messagingSenderId: '851479812076',
    projectId: 'ets-ppb-1512',
    storageBucket: 'ets-ppb-1512.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:851479812076:ios:8ba04be44f9afb306712c9',
    messagingSenderId: '851479812076',
    projectId: 'ets-ppb-1512',
    storageBucket: 'ets-ppb-1512.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
    appId: '1:851479812076:web:4f4075f7004aeba66712c9',
    messagingSenderId: '851479812076',
    projectId: 'ets-ppb-1512',
    authDomain: 'ets-ppb-1512.firebaseapp.com',
    storageBucket: 'ets-ppb-1512.firebasestorage.app',
  );
}
